export const getLanguage = (lang: string | null = "en") => {
  if (lang === "en") {
    return {
      success: "Success",
      serverError: "Internal server error",
      unauthorized: "Unauthorized",
      idNotFound: "Id not found!",
      notFound: "Not found!",
      unauthorizedUser: "Unauthorized user!",
      userNotExisted: "User not existed",
      somethingWentWrong: "Something went wrong",
      noUserFound: "No user found",
      wrongOtp: "Wrong otp",
      otpExpired: "Otp Expired",
      paramsMissing: "Params missing",
      questionExist: "Question exist",
      userNotFound: "User not found",
      pleaseProvideId: "Please provide id!",
      noAdFound: "No advertisement found!",
      fileRequired: "File Required!",
      removed: "Removed!",
      threadNotFound: "Thread not found",
      otpSent: "We sent otp to your phone number please check",
      invalidCredentials: "Invalid Credentials!",
      userExist: "User existed with this number!",
      adNotFound: "Advertisement Not found!",
    }
  }

  if (lang === "ar") {
    return {
      success: "نجاح",
      serverError: "خطأ داخلي في الخادم",
      unauthorized: "غير مصرح",
      idNotFound: "لم يتم العثور على المعرف!",
      notFound: "غير موجود!",
      unauthorizedUser: "مستخدم غير مصرح!",
      userNotExisted: "المستخدم غير موجود",
      somethingWentWrong: "حدث خطأ ما",
      noUserFound: "لم يتم العثور على مستخدم",
      wrongOtp: "رمز التحقق خاطئ",
      otpExpired: "انتهت صلاحية رمز التحقق",
      paramsMissing: "المعلمات مفقودة",
      questionExist: "السؤال موجود",
      userNotFound: "المستخدم غير موجود",
      pleaseProvideId: "يرجى تقديم المعرف!",
      noAdFound: "لم يتم العثور على إعلان!",
      fileRequired: "الملف مطلوب!",
      removed: "تمت الإزالة!",
      threadNotFound: "لم يتم العثور على المحادثة",
      otpSent: "أرسلنا رمز التحقق إلى رقم هاتفك، يرجى التحقق",
      invalidCredentials: "بيانات الاعتماد غير صالحة!",
      userExist: "يوجد مستخدم بهذا الرقم!",
      adNotFound: "لم يتم العثور على الإعلان!",
    }
  }

  if (lang === "fr") {
    return {
      success: "Succès",
      serverError: "Erreur interne du serveur",
      unauthorized: "Non autorisé",
      idNotFound: "ID introuvable !",
      notFound: "Introuvable !",
      unauthorizedUser: "Utilisateur non autorisé !",
      userNotExisted: "Utilisateur inexistant",
      somethingWentWrong: "Quelque chose s'est mal passé",
      noUserFound: "Aucun utilisateur trouvé",
      wrongOtp: "Code OTP incorrect",
      otpExpired: "Le code OTP a expiré",
      paramsMissing: "Paramètres manquants",
      questionExist: "La question existe déjà",
      userNotFound: "Utilisateur non trouvé",
      pleaseProvideId: "Veuillez fournir l'ID !",
      noAdFound: "Aucune annonce trouvée !",
      fileRequired: "Fichier requis !",
      removed: "Supprimé !",
      threadNotFound: "Fil de discussion introuvable",
      otpSent:
        "Nous avons envoyé un code OTP à votre numéro, veuillez vérifier",
      invalidCredentials: "Identifiants invalides !",
      userExist: "Un utilisateur existe déjà avec ce numéro !",
      adNotFound: "Annonce introuvable !",
    }
  } else {
    return {
      success: "Success",
      serverError: "Internal server error",
      unauthorized: "Unauthorized",
      idNotFound: "Id not found!",
      notFound: "Not found!",
      unauthorizedUser: "Unauthorized user!",
      userNotExisted: "User not existed",
      somethingWentWrong: "Something went wrong",
      noUserFound: "No user found",
      wrongOtp: "Wrong otp",
      otpExpired: "Otp Expired",
      paramsMissing: "Params missing",
      questionExist: "Question exist",
      userNotFound: "User not found",
      pleaseProvideId: "Please provide id!",
      noAdFound: "No advertisement found!",
      fileRequired: "File Required!",
      removed: "Removed!",
      threadNotFound: "Thread not found",
      otpSent: "We sent otp to your phone number please check",
      invalidCredentials: "Invalid Credentials!",
      userExist: "User existed with this number!",
      adNotFound: "Advertisement Not found!",
    }
  }
}
